### ISSUE TITLE
0.1 release and beyond

### ISSUE THREAD

**Issue by LetsMelon** [LetsMelon/rusvid#2]
## Must be there:

- [x] animation system, see #3 and 43bd2facbd30182963a119ad0558816ec1707046
- [x] image renderer, see #4
- [x] no `.unwrap()`
- [x] no `todo!()`, see #12
- [x] use `derive(Debug)`, see #12
- [ ] cli?
- [ ] docs, see branch [origin/add_documentation](https://github.com/LetsMelon/rusvid/tree/add_documentation)

## Nice to have:

- [ ] no `unsafe {}` code-block (possible?)
- [ ] custom error enum
- [ ] logging
- [ ] resolve todos
- [x] more tests, like 9e1cc8fa1862cf3c78adf1eae7cfef2a37961288 or 31188bf032bc20ce6dec3d2afce8dce635897700
- [x] #14

**Comment by LetsMelon** [comment]
Published on [crates.io](https://crates.io/crates/rusvid_lib).
